=== nauvalazhar/selia/public/schemas/item.v1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "type": {
      "anyOf": [
        {
          "type": "string",
          "enum": [
            "component",
            "block",
            "hook",
            "util",
            "config"
          ]
        },
        {
          "type": "string"
        }
      ]
    },
    "dependencies": {
      "type": "object",
      "properties": {
        "npm": {
          "type": "object",
          "propertyNames": {
            "type": "string"
          },
          "additionalProperties": {
            "type": "string"
          }
        },
        "items": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false
    },
    "files": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "content": {
            "type": "string"
          },
          "target": {
            "type": "string"
          },
          "path": {
            "type": "string"
          },
          "type": {
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "component",
                  "block",
                  "hook",
                  "util",
                  "config"
                ]
              },
              {
                "type": "string"
              }
            ]
          }
        },
        "required": [
          "name",
          "target"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "name",
    "type",
    "files"
  ],
  "additionalProperties": false
}

=== nauvalazhar/selia/public/registry/alert-dialog.json
{
  "name": "alert-dialog",
  "type": "component",
  "dependencies": {
    "items": [
      "button"
    ]
  },
  "files": [
    {
      "name": "alert-dialog.tsx",
      "target": "components",
      "content": "'use client';\r\n\r\nimport { AlertDialog as BaseAlertDialog } from '@base-ui/react/alert-dialog';\r\nimport { buttonVariants } from './button';\r\nimport { cn } from '#utils';\r\n\r\nexport function AlertDialog({\r\n  ...props\r\n}: React.ComponentProps<typeof BaseAlertDialog.Root>) {\r\n  return <BaseAlertDialog.Root data-slot=\"alert-dialog\" {...props} />;\r\n}\r\n\r\nexport function AlertDialogTrigger({\r\n  children,\r\n  ...props\r\n}: React.ComponentProps<typeof BaseAlertDialog.Trigger>) {\r\n  return (\r\n    <BaseAlertDialog.Trigger data-slot=\"alert-dialog-trigger\" {...props}>\r\n      {children}\r\n    </BaseAlertDialog.Trigger>\r\n  );\r\n}\r\n\r\nexport function AlertDialogPopup({\r\n  className,\r\n  children,\r\n  ...props\r\n}: React.ComponentProps<typeof BaseAlertDialog.Popup>) {\r\n  return (\r\n    <BaseAlertDialog.Portal>\r\n      <BaseAlertDialog.Backdrop\r\n        className={cn(\r\n          'fixed inset-0 min-h-dvh bg-black/60 transition-[color,opacity] backdrop-blur-sm',\r\n          'data-[starting-style]:opacity-0 data-[ending-style]:opacity-0',\r\n        )}\r\n      />\r\n      <BaseAlertDialog.Popup\r\n        data-slot=\"alert-dialog-popup\"\r\n        {...props}\r\n        className={cn(\r\n          'fixed left-1/2 -translate-x-1/2 -translate-y-1/2',\r\n          'top-[calc(50%+1.25rem*var(--nested-dialogs))]',\r\n          'bg-dialog text-dialog-foreground backdrop-blur-sm',\r\n          'ring ring-dialog-border rounded-xl shadow',\r\n          'scale-[calc(1-0.1*var(--nested-dialogs))]',\r\n          'outline-none transition-all w-md max-w-[calc(100%-2rem)]',\r\n          'data-[nested-dialog-open]:after:absolute',\r\n          'data-[nested-dialog-open]:after:inset-0',\r\n          'data-[nested-dialog-open]:after:rounded-xl',\r\n          'data-[nested-dialog-open]:after:bg-black/20',\r\n          'data-[nested-dialog-open]:after:z-10',\r\n          'data-[starting-style]:opacity-0 data-[ending-style]:opacity-0',\r\n          'data-[starting-style]:scale-90 data-[ending-style]:scale-90',\r\n          className,\r\n        )}\r\n      >\r\n        {children}\r\n      </BaseAlertDialog.Popup>\r\n    </BaseAlertDialog.Portal>\r\n  );\r\n}\r\n\r\nexport function AlertDialogHeader({\r\n  className,\r\n  children,\r\n  ...props\r\n}: React.ComponentProps<'header'>) {\r\n  return (\r\n    <header\r\n      data-slot=\"alert-dialog-header\"\r\n      {...props}\r\n      className={cn('px-6 pt-4.5 flex items-center gap-3.5', className)}\r\n    >\r\n      {children}\r\n    </header>\r\n  );\r\n}\r\n\r\nexport function AlertDialogTitle({\r\n  className,\r\n  children,\r\n  ...props\r\n}: React.ComponentProps<typeof BaseAlertDialog.Title>) {\r\n  return (\r\n    <BaseAlertDialog.Title\r\n      data-slot=\"alert-dialog-title\"\r\n      {...props}\r\n      className={cn('text-xl font-semibold', className)}\r\n    >\r\n      {children}\r\n    </BaseAlertDialog.Title>\r\n  );\r\n}\r\n\r\nexport function AlertDialogBody({\r\n  className,\r\n  children,\r\n  ...props\r\n}: React.ComponentProps<'div'>) {\r\n  return (\r\n    <div\r\n      data-slot=\"alert-dialog-body\"\r\n      {...props}\r\n      className={cn('px-6 py-4.5', className)}\r\n    >\r\n      {children}\r\n    </div>\r\n  );\r\n}\r\n\r\nexport function AlertDialogDescription({\r\n  className,\r\n  children,\r\n  ...props\r\n}: React.ComponentProps<typeof BaseAlertDialog.Description>) {\r\n  return (\r\n    <BaseAlertDialog.Description\r\n      data-slot=\"alert-dialog-description\"\r\n      {...props}\r\n      className={cn('text-muted leading-relaxed', className)}\r\n    >\r\n      {children}\r\n    </BaseAlertDialog.Description>\r\n  );\r\n}\r\n\r\nexport function AlertDialogFooter({\r\n  className,\r\n  children,\r\n  ...props\r\n}: React.ComponentProps<'footer'>) {\r\n  return (\r\n    <footer\r\n      data-slot=\"alert-dialog-footer\"\r\n      {...props}\r\n      className={cn(\r\n        'flex items-center justify-end gap-1.5',\r\n        'px-6 py-3.5 bg-dialog-footer border-t border-dialog-border rounded-b-xl',\r\n        className,\r\n      )}\r\n    >\r\n      {children}\r\n    </footer>\r\n  );\r\n}\r\n\r\nexport function AlertDialogClose({\r\n  className,\r\n  render,\r\n  children,\r\n  ...props\r\n}: React.ComponentProps<typeof BaseAlertDialog.Close>) {\r\n  return (\r\n    <BaseAlertDialog.Close\r\n      data-slot=\"alert-dialog-close\"\r\n      render={render}\r\n      {...props}\r\n      className={cn(!render && buttonVariants({ variant: 'plain' }), className)}\r\n    >\r\n      {children}\r\n    </BaseAlertDialog.Close>\r\n  );\r\n}\r\n"
    }
  ]
}

=== nauvalazhar/selia/public/registry/pagination.json
{
  "name": "pagination",
  "type": "component",
  "dependencies": {
    "items": [
      "button"
    ]
  },
  "files": [
    {
      "name": "pagination.tsx",
      "target": "components",
      "content": "'use client';\r\n\r\nimport { useRender } from '@base-ui/react/use-render';\r\nimport { buttonVariants } from './button';\r\nimport { cn } from '#utils';\r\n\r\nexport function Pagination({ ...props }: React.ComponentProps<'nav'>) {\r\n  return (\r\n    <nav\r\n      data-slot=\"pagination\"\r\n      aria-label=\"Pagination\"\r\n      {...props}\r\n      className={cn('flex justify-center', props.className)}\r\n    />\r\n  );\r\n}\r\n\r\nexport function PaginationList({\r\n  children,\r\n  ...props\r\n}: React.ComponentProps<'ul'>) {\r\n  return (\r\n    <ul\r\n      data-slot=\"pagination-list\"\r\n      className=\"flex items-center gap-1\"\r\n      {...props}\r\n    >\r\n      {children}\r\n    </ul>\r\n  );\r\n}\r\n\r\nexport function PaginationItem({\r\n  children,\r\n  ...props\r\n}: React.ComponentProps<'li'>) {\r\n  return (\r\n    <li data-slot=\"pagination-item\" {...props}>\r\n      {children}\r\n    </li>\r\n  );\r\n}\r\n\r\nexport function PaginationButton({\r\n  active,\r\n  disabled,\r\n  render,\r\n  ...props\r\n}: useRender.ComponentProps<'button'> & {\r\n  active?: boolean;\r\n  disabled?: boolean;\r\n}) {\r\n  return useRender({\r\n    defaultTagName: 'button',\r\n    render,\r\n    props: {\r\n      'data-slot': 'pagination-button',\r\n      'aria-current': active ? 'page' : undefined,\r\n      'aria-disabled': disabled ? true : undefined,\r\n      className: cn(\r\n        buttonVariants({\r\n          variant: active ? 'secondary' : 'plain',\r\n        }),\r\n        'cursor-pointer',\r\n        active && 'pointer-events-none',\r\n        disabled && 'pointer-events-none opacity-70',\r\n        props.className,\r\n      ),\r\n      ...props,\r\n    },\r\n  });\r\n}\r\n"
    }
  ]
}

=== nauvalazhar/selia/public/registry/select.json
{
  "name": "select",
  "type": "component",
  "dependencies": {
    "items": [
      "chip"
    ]
  },
  "files": [
    {
      "name": "select.tsx",
      "target": "components",
      "content": "'use client';\r\n\r\nimport * as React from 'react';\r\nimport { Select as BaseSelect } from '@base-ui/react/select';\r\nimport { cn } from '#utils';\r\nimport { cva, type VariantProps } from 'class-variance-authority';\r\nimport { Chip } from './chip';\r\n\r\nexport type SelectItem = {\r\n  value: string;\r\n  label: React.ReactNode;\r\n  icon?: React.ReactNode;\r\n};\r\n\r\nexport function Select({\r\n  ...props\r\n}: React.ComponentProps<typeof BaseSelect.Root>) {\r\n  return <BaseSelect.Root {...props} />;\r\n}\r\n\r\nexport const selectTriggerVariants = cva(\r\n  [\r\n    'h-9.5 px-3.5 w-full bg-input rounded placeholder:text-dimmed transition-all',\r\n    'focus:outline-0 focus:ring-primary focus:ring-2',\r\n    'flex items-center gap-2.5 cursor-default',\r\n    'data-disabled:opacity-70 data-disabled:pointer-events-none',\r\n  ],\r\n  {\r\n    variants: {\r\n      variant: {\r\n        default:\r\n          'bg-input ring ring-input-border hover:ring-input-accent-border shadow-input',\r\n        subtle:\r\n          'bg-input/60 ring ring-input-border hover:ring-input-accent-border shadow-input',\r\n        plain: 'bg-transparent hover:bg-accent',\r\n      },\r\n    },\r\n    defaultVariants: {\r\n      variant: 'default',\r\n    },\r\n  },\r\n);\r\n\r\nexport function SelectTrigger({\r\n  className,\r\n  children,\r\n  variant,\r\n  ...props\r\n}: React.ComponentProps<typeof BaseSelect.Trigger> &\r\n  VariantProps<typeof selectTriggerVariants>) {\r\n  return (\r\n    <BaseSelect.Trigger\r\n      data-slot=\"select-trigger\"\r\n      className={cn(selectTriggerVariants({ variant, className }))}\r\n      {...props}\r\n    >\r\n      {children}\r\n\r\n      <BaseSelect.Icon className=\"ml-auto size-4 text-muted pointer-events-none\">\r\n        <svg\r\n          xmlns=\"http://www.w3.org/2000/svg\"\r\n          viewBox=\"0 0 24 24\"\r\n          fill=\"none\"\r\n          stroke=\"currentColor\"\r\n          strokeWidth=\"2\"\r\n          strokeLinecap=\"round\"\r\n          strokeLinejoin=\"round\"\r\n        >\r\n          <polyline points=\"6 9 12 15 18 9\" />\r\n        </svg>\r\n      </BaseSelect.Icon>\r\n    </BaseSelect.Trigger>\r\n  );\r\n}\r\n\r\nexport function SelectValue({\r\n  className,\r\n  placeholder = 'Select an option',\r\n  ...props\r\n}: React.ComponentProps<typeof BaseSelect.Value> & {\r\n  placeholder?: string;\r\n}) {\r\n  return (\r\n    <BaseSelect.Value\r\n      data-slot=\"select-value\"\r\n      className={cn(className)}\r\n      {...props}\r\n    >\r\n      {(value: string | SelectItem | null) => (\r\n        <SelectRenderValue value={value} placeholder={placeholder} />\r\n      )}\r\n    </BaseSelect.Value>\r\n  );\r\n}\r\n\r\nfunction SelectRenderValue({\r\n  value,\r\n  placeholder,\r\n}: {\r\n  value: string | SelectItem | SelectItem[] | null;\r\n  placeholder: string;\r\n}) {\r\n  if (!value || (Array.isArray(value) && value.length === 0)) {\r\n    return <span className=\"text-dimmed\">{placeholder}</span>;\r\n  }\r\n\r\n  if (Array.isArray(value)) {\r\n    const firstValue = value[0];\r\n    const firstValueLabel =\r\n      typeof firstValue === 'object' ? firstValue.label : firstValue;\r\n    const additionalValues =\r\n      value.length > 1 ? (\r\n        <Chip className=\"ml-1.5\" size=\"sm\">\r\n          +{value.length - 1} more\r\n        </Chip>\r\n      ) : (\r\n        ''\r\n      );\r\n\r\n    return (\r\n      <>\r\n        {firstValueLabel}\r\n        {additionalValues}\r\n      </>\r\n    );\r\n  }\r\n\r\n  if (typeof value === 'object') {\r\n    return (\r\n      <div className=\"flex items-center gap-2.5 select-none *:[svg]:size-4 *:[svg]:text-popover-foreground\">\r\n        {value.icon}\r\n        <span className=\"text-popover-foreground\">{value.label}</span>\r\n      </div>\r\n    );\r\n  }\r\n\r\n  return <span className=\"text-popover-foreground select-none\">{value}</span>;\r\n}\r\n\r\nexport function SelectPopup({\r\n  children,\r\n  className,\r\n  align,\r\n  alignOffset,\r\n  side,\r\n  sideOffset,\r\n  anchor,\r\n  sticky,\r\n  positionMethod,\r\n  ...props\r\n}: React.ComponentProps<typeof BaseSelect.Popup> &\r\n  VariantProps<typeof selectTriggerVariants> & {\r\n    align?: BaseSelect.Positioner.Props['align'];\r\n    alignOffset?: BaseSelect.Positioner.Props['alignOffset'];\r\n    side?: BaseSelect.Positioner.Props['side'];\r\n    sideOffset?: BaseSelect.Positioner.Props['sideOffset'];\r\n    anchor?: BaseSelect.Positioner.Props['anchor'];\r\n    sticky?: BaseSelect.Positioner.Props['sticky'];\r\n    positionMethod?: BaseSelect.Positioner.Props['positionMethod'];\r\n  }) {\r\n  return (\r\n    <BaseSelect.Portal>\r\n      <BaseSelect.Backdrop />\r\n      <BaseSelect.Positioner\r\n        align={align}\r\n        alignOffset={alignOffset}\r\n        side={side}\r\n        sideOffset={sideOffset || 6}\r\n        anchor={anchor}\r\n        sticky={sticky}\r\n        positionMethod={positionMethod}\r\n      >\r\n        <BaseSelect.ScrollUpArrow className=\"top-1 left-1 right-1 z-10 absolute rounded h-5 text-xs text-popover-foreground flex items-center justify-around bg-popover-accent\" />\r\n        <BaseSelect.Popup\r\n          data-slot=\"select-popup\"\r\n          {...props}\r\n          className={cn(\r\n            'group origin-(--transform-origin) bg-popover ring ring-popover-border rounded shadow-popover',\r\n            'p-1 outline-none max-lg:w-(--anchor-width)',\r\n            className,\r\n          )}\r\n        >\r\n          <BaseSelect.Arrow />\r\n          {children}\r\n        </BaseSelect.Popup>\r\n        <BaseSelect.ScrollDownArrow className=\"bottom-1 left-1 right-1 z-10 absolute rounded h-5 text-xs text-popover-foreground flex items-center justify-around bg-popover-accent\" />\r\n      </BaseSelect.Positioner>\r\n    </BaseSelect.Portal>\r\n  );\r\n}\r\n\r\nexport function SelectList({\r\n  className,\r\n  ...props\r\n}: React.ComponentProps<typeof BaseSelect.List>) {\r\n  return (\r\n    <BaseSelect.List\r\n      data-slot=\"select-list\"\r\n      className={cn(\r\n        'space-y-0.5 max-h-(--available-height) overflow-y-auto relative',\r\n        className,\r\n      )}\r\n      {...props}\r\n    />\r\n  );\r\n}\r\n\r\nexport function SelectItem({\r\n  className,\r\n  children,\r\n  ...props\r\n}: React.ComponentProps<typeof BaseSelect.Item>) {\r\n  return (\r\n    <BaseSelect.Item\r\n      data-slot=\"select-item\"\r\n      className={cn(\r\n        'flex items-center text-popover-foreground py-2.5 px-3 gap-3.5 rounded select-none',\r\n        'group-data-[side=none]:min-w-[calc(var(--anchor-width))]',\r\n        'data-[highlighted]:bg-popover-accent data-[selected]:bg-popover-accent',\r\n        'focus-visible:outline-none',\r\n        'data-disabled:opacity-70 data-disabled:pointer-events-none',\r\n        className,\r\n      )}\r\n      {...props}\r\n    >\r\n      <BaseSelect.ItemText className=\"flex items-center gap-2.5 *:[svg]:size-4\">\r\n        {children}\r\n      </BaseSelect.ItemText>\r\n      <BaseSelect.ItemIndicator className=\"ml-auto\">\r\n        <svg\r\n          className=\"size-4 text-primary\"\r\n          xmlns=\"http://www.w3.org/2000/svg\"\r\n          viewBox=\"0 0 24 24\"\r\n          fill=\"none\"\r\n          stroke=\"currentColor\"\r\n          strokeWidth=\"3\"\r\n          strokeLinecap=\"round\"\r\n          strokeLinejoin=\"round\"\r\n        >\r\n          <polyline points=\"20 6 9 17 4 12\" />\r\n        </svg>\r\n      </BaseSelect.ItemIndicator>\r\n    </BaseSelect.Item>\r\n  );\r\n}\r\n\r\nexport function SelectGroup({\r\n  className,\r\n  ...props\r\n}: React.ComponentProps<typeof BaseSelect.Group>) {\r\n  return (\r\n    <BaseSelect.Group\r\n      data-slot=\"select-group\"\r\n      className={cn('space-y-0.5', className)}\r\n      {...props}\r\n    />\r\n  );\r\n}\r\n\r\nexport function SelectGroupLabel({\r\n  className,\r\n  ...props\r\n}: React.ComponentProps<typeof BaseSelect.GroupLabel>) {\r\n  return (\r\n    <BaseSelect.GroupLabel\r\n      data-slot=\"select-group-label\"\r\n      className={cn('px-3 py-1.5 text-sm font-medium text-dimmed', className)}\r\n      {...props}\r\n    />\r\n  );\r\n}\r\n\r\nexport function SelectSeparator({\r\n  className,\r\n  ...props\r\n}: React.ComponentProps<typeof BaseSelect.Separator>) {\r\n  return (\r\n    <BaseSelect.Separator\r\n      data-slot=\"select-separator\"\r\n      className={cn('h-px my-1 bg-popover-separator', className)}\r\n      {...props}\r\n    />\r\n  );\r\n}\r\n"
    }
  ]
}

=== nauvalazhar/selia/public/registry/toast.json
{
  "name": "toast",
  "type": "component",
  "dependencies": {
    "items": [
      "button"
    ]
  },
  "files": [
    {
      "name": "toast.tsx",
      "target": "components",
      "content": "'use client';\r\n\r\nimport { Toast as BaseToast, type ToastObject } from '@base-ui/react/toast';\r\nimport { buttonVariants } from './button';\r\nimport { cn } from '#utils';\r\n\r\nexport const toastManager = BaseToast.createToastManager();\r\nexport const anchoredToastManager = BaseToast.createToastManager();\r\n\r\nexport function Toast() {\r\n  return (\r\n    <>\r\n      <BaseToast.Provider toastManager={toastManager}>\r\n        <StackedToasts />\r\n      </BaseToast.Provider>\r\n      <BaseToast.Provider toastManager={anchoredToastManager}>\r\n        <AnchoredToasts />\r\n      </BaseToast.Provider>\r\n    </>\r\n  );\r\n}\r\n\r\nfunction StackedToasts() {\r\n  const { toasts } = BaseToast.useToastManager();\r\n\r\n  return (\r\n    <BaseToast.Portal>\r\n      <BaseToast.Viewport className=\"fixed top-2 md:top-4 right-0 left-0 mx-2 md:mx-auto flex\">\r\n        {toasts.map((toast) => (\r\n          <BaseToast.Root\r\n            key={toast.id}\r\n            toast={toast}\r\n            swipeDirection=\"up\"\r\n            className={cn(\r\n              'absolute right-0 top-0 left-0 z-[calc(1000-var(--toast-index))] mx-auto w-sm max-w-full origin-top',\r\n              'rounded border border-toast-border bg-toast p-4 shadow-lg select-none h-(--height)',\r\n              'after:absolute after:bottom-full after:left-0 after:h-[calc(var(--gap)+1px)] after:w-full',\r\n              '[--gap:0.75rem] [--peek:0.75rem] [--scale:calc(max(0,1-(var(--toast-index)*0.1)))] [--shrink:calc(1-var(--scale))]',\r\n              '[--height:var(--toast-frontmost-height,var(--toast-height))] [--offset-y:calc(var(--toast-offset-y)+(var(--toast-index)*var(--gap))+var(--toast-swipe-movement-y))]',\r\n              '[transform:translateX(var(--toast-swipe-movement-x))_translateY(calc(var(--toast-swipe-movement-y)+(var(--toast-index)*var(--peek))+(var(--shrink)*var(--height))))_scale(var(--scale))]',\r\n              '[transition:transform_0.5s_cubic-bezier(0.22,1,0.36,1),opacity_0.5s,height_0.15s]',\r\n              'data-[starting-style]:[transform:translateY(-150%)]',\r\n              'data-[ending-style]:data-[swipe-direction=down]:[transform:translateY(calc(var(--toast-swipe-movement-y)+150%))]',\r\n              'data-[ending-style]:data-[swipe-direction=left]:[transform:translateX(calc(var(--toast-swipe-movement-x)-150%))_translateY(var(--offset-y))]',\r\n              'data-[ending-style]:data-[swipe-direction=right]:[transform:translateX(calc(var(--toast-swipe-movement-x)+150%))_translateY(var(--offset-y))]',\r\n              'data-[ending-style]:data-[swipe-direction=up]:[transform:translateY(calc(var(--toast-swipe-movement-y)-150%))]',\r\n              '[&[data-ending-style]:not([data-limited]):not([data-swipe-direction])]:[transform:translateY(-150%)]',\r\n              'data-[ending-style]:opacity-0',\r\n              'data-[limited]:opacity-0',\r\n              'data-[expanded]:h-[var(--toast-height)]',\r\n              'data-[expanded]:data-[ending-style]:data-[swipe-direction=down]:[transform:translateY(calc(var(--toast-swipe-movement-y)+150%))]',\r\n              'data-[expanded]:data-[ending-style]:data-[swipe-direction=left]:[transform:translateX(calc(var(--toast-swipe-movement-x)-150%))_translateY(var(--offset-y))]',\r\n              'data-[expanded]:data-[ending-style]:data-[swipe-direction=right]:[transform:translateX(calc(var(--toast-swipe-movement-x)+150%))_translateY(var(--offset-y))]',\r\n              'data-[expanded]:data-[ending-style]:data-[swipe-direction=up]:[transform:translateY(calc(var(--toast-swipe-movement-y)-150%))]',\r\n              'data-[expanded]:[transform:translateX(var(--toast-swipe-movement-x))_translateY(calc(var(--offset-y)))]',\r\n            )}\r\n          >\r\n            <ToastContent toast={toast} />\r\n          </BaseToast.Root>\r\n        ))}\r\n      </BaseToast.Viewport>\r\n    </BaseToast.Portal>\r\n  );\r\n}\r\n\r\nfunction AnchoredToasts() {\r\n  const { toasts } = BaseToast.useToastManager();\r\n\r\n  return (\r\n    <BaseToast.Portal>\r\n      <BaseToast.Viewport className=\"outline-0\">\r\n        {toasts.map((toast) => (\r\n          <BaseToast.Positioner\r\n            key={toast.id}\r\n            toast={toast}\r\n            className=\"z-[calc(1000-var(--toast-index))]\"\r\n          >\r\n            <BaseToast.Root\r\n              toast={toast}\r\n              className={cn(\r\n                'group flex w-max origin-(--transform-origin) flex-col outline-none',\r\n                'shadow bg-toast border border-toast-border rounded',\r\n                'transition-[transform,scale,opacity]',\r\n                'data-ending-style:scale-90 data-ending-style:opacity-0',\r\n                'data-starting-style:scale-90 data-starting-style:opacity-0',\r\n                toast.data?.size === 'sm' ? 'p-2' : 'p-4',\r\n              )}\r\n            >\r\n              <ToastContent toast={toast} />\r\n            </BaseToast.Root>\r\n          </BaseToast.Positioner>\r\n        ))}\r\n      </BaseToast.Viewport>\r\n    </BaseToast.Portal>\r\n  );\r\n}\r\n\r\nfunction ToastContent({ toast }: { toast: ToastObject<Object> }) {\r\n  return (\r\n    <BaseToast.Content\r\n      data-slot=\"toast-content\"\r\n      className={cn(\r\n        'overflow-hidden transition-opacity data-behind:pointer-events-none data-behind:opacity-0',\r\n        'data-expanded:opacity-100 data-expanded:pointer-events-auto',\r\n        'flex gap-x-2.5 gap-y-0.5 items-center',\r\n      )}\r\n    >\r\n      {toast.type && (\r\n        <ToastIcon type={toast.type}>{icons[toast.type]}</ToastIcon>\r\n      )}\r\n      <div className=\"w-full flex justify-between flex-col md:flex-row items-start\">\r\n        <div>\r\n          <BaseToast.Title\r\n            data-slot=\"toast-title\"\r\n            className=\"text-foreground font-medium\"\r\n          />\r\n          <BaseToast.Description\r\n            data-slot=\"toast-description\"\r\n            className=\"text-muted col-start-1\"\r\n          />\r\n        </div>\r\n        <BaseToast.Action\r\n          data-slot=\"toast-action\"\r\n          className={cn(\r\n            'text-sm md:ml-auto shrink-0 mt-2 md:mt-0 self-center',\r\n            buttonVariants({ variant: 'tertiary', size: 'xs' }),\r\n          )}\r\n        />\r\n      </div>\r\n    </BaseToast.Content>\r\n  );\r\n}\r\n\r\nfunction ToastIcon({\r\n  type,\r\n  children,\r\n}: {\r\n  type?: string;\r\n  children: React.ReactNode;\r\n}) {\r\n  return (\r\n    <div\r\n      data-slot=\"toast-icon\"\r\n      className={cn(\r\n        '*:[svg]:w-4.5 self-start',\r\n        type === 'success' && '*:[svg]:fill-success/20 *:[svg]:stroke-success',\r\n        type === 'info' && '*:[svg]:fill-info/20 *:[svg]:stroke-info',\r\n        type === 'warning' && '*:[svg]:fill-warning/20 *:[svg]:stroke-warning',\r\n        type === 'danger' && '*:[svg]:fill-danger/20 *:[svg]:stroke-danger',\r\n      )}\r\n    >\r\n      {children}\r\n    </div>\r\n  );\r\n}\r\n\r\nconst icons: Record<string, React.ReactNode> = {\r\n  loading: (\r\n    <svg\r\n      xmlns=\"http://www.w3.org/2000/svg\"\r\n      viewBox=\"0 0 24 24\"\r\n      fill=\"none\"\r\n      stroke=\"currentColor\"\r\n      strokeWidth=\"2\"\r\n      strokeLinecap=\"round\"\r\n      strokeLinejoin=\"round\"\r\n      className=\"size-4.5 animate-spin\"\r\n    >\r\n      <path d=\"M21 12a9 9 0 1 1-6.219-8.56\" />\r\n    </svg>\r\n  ),\r\n  success: (\r\n    <svg\r\n      xmlns=\"http://www.w3.org/2000/svg\"\r\n      viewBox=\"0 0 24 24\"\r\n      fill=\"none\"\r\n      stroke=\"currentColor\"\r\n      strokeWidth=\"2\"\r\n      strokeLinecap=\"round\"\r\n      strokeLinejoin=\"round\"\r\n    >\r\n      <circle cx=\"12\" cy=\"12\" r=\"10\" />\r\n      <path d=\"m9 12 2 2 4-4\" />\r\n    </svg>\r\n  ),\r\n  info: (\r\n    <svg\r\n      xmlns=\"http://www.w3.org/2000/svg\"\r\n      viewBox=\"0 0 24 24\"\r\n      fill=\"none\"\r\n      stroke=\"currentColor\"\r\n      strokeWidth=\"2\"\r\n      strokeLinecap=\"round\"\r\n      strokeLinejoin=\"round\"\r\n    >\r\n      <circle cx=\"12\" cy=\"12\" r=\"10\" />\r\n      <path d=\"M12 16v-4\" />\r\n      <path d=\"M12 8h.01\" />\r\n    </svg>\r\n  ),\r\n  warning: (\r\n    <svg\r\n      xmlns=\"http://www.w3.org/2000/svg\"\r\n      viewBox=\"0 0 24 24\"\r\n      fill=\"none\"\r\n      stroke=\"currentColor\"\r\n      strokeWidth=\"2\"\r\n      strokeLinecap=\"round\"\r\n      strokeLinejoin=\"round\"\r\n    >\r\n      <path d=\"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3\" />\r\n      <path d=\"M12 9v4\" />\r\n      <path d=\"M12 17h.01\" />\r\n    </svg>\r\n  ),\r\n  danger: (\r\n    <svg\r\n      xmlns=\"http://www.w3.org/2000/svg\"\r\n      viewBox=\"0 0 24 24\"\r\n      fill=\"none\"\r\n      stroke=\"currentColor\"\r\n      strokeWidth=\"2\"\r\n      strokeLinecap=\"round\"\r\n      strokeLinejoin=\"round\"\r\n    >\r\n      <circle cx=\"12\" cy=\"12\" r=\"10\" />\r\n      <path d=\"m15 9-6 6\" />\r\n      <path d=\"m9 9 6 6\" />\r\n    </svg>\r\n  ),\r\n};\r\n"
    }
  ]
}

=== nauvalazhar/selia/public/registry/command.json
{
  "name": "command",
  "type": "component",
  "dependencies": {
    "items": [
      "dialog"
    ]
  },
  "files": [
    {
      "name": "command.tsx",
      "target": "components",
      "content": "'use client';\n\nimport { cn } from '#utils';\nimport { Dialog, DialogBody, DialogPopup, DialogTrigger } from './dialog';\n\nexport function Command({ ...props }: React.ComponentProps<typeof Dialog>) {\n  return <Dialog {...props} />;\n}\n\nexport function CommandTrigger({\n  className,\n  ...props\n}: React.ComponentProps<typeof DialogTrigger>) {\n  return (\n    <DialogTrigger\n      data-slot=\"command-trigger\"\n      {...props}\n      className={cn(className)}\n    />\n  );\n}\n\nexport function CommandContent({\n  className,\n  ...props\n}: React.ComponentProps<typeof DialogPopup>) {\n  return (\n    <DialogPopup\n      {...props}\n      className={cn(\n        'p-1 bg-dialog-footer/90 md:min-w-xl',\n        '**:data-[slot=autocomplete-list]:h-[min(27rem,50dvh)]',\n        '**:data-[slot=autocomplete-empty]:h-[min(27rem,50dvh)]',\n        '**:data-[slot=autocomplete-input]:h-11',\n        '**:data-[slot=input-group]:px-2.5',\n        '**:data-[slot=input-group]:border-b',\n        '**:data-[slot=input-group]:border-dialog-border',\n        className,\n      )}\n    />\n  );\n}\n\nexport function CommandBody({\n  className,\n  ...props\n}: React.ComponentProps<typeof DialogBody>) {\n  return (\n    <DialogBody\n      {...props}\n      className={cn(\n        'space-y-0 bg-dialog border border-dialog-border rounded-xl',\n        'bg-dialog shadow p-0',\n        '**:data-[slot=autocomplete-list]:px-2.5 **:data-[slot=autocomplete-list]:py-1.5',\n        className,\n      )}\n    ></DialogBody>\n  );\n}\n\nexport function CommandFooter({\n  className,\n  ...props\n}: React.ComponentProps<'footer'>) {\n  return (\n    <footer\n      data-slot=\"command-footer\"\n      {...props}\n      className={cn('px-5 pt-3 pb-2.5 flex items-center gap-6', className)}\n    />\n  );\n}\n\nexport function CommandFooterItem({\n  className,\n  ...props\n}: React.ComponentProps<'div'>) {\n  return (\n    <div\n      data-slot=\"command-footer-item\"\n      {...props}\n      className={cn('flex items-center gap-2.5', className)}\n    />\n  );\n}\n\nexport function CommandFooterText({\n  className,\n  ...props\n}: React.ComponentProps<'span'>) {\n  return (\n    <span\n      data-slot=\"command-footer-text\"\n      {...props}\n      className={cn('text-sm text-muted font-medium', className)}\n    />\n  );\n}\n"
    }
  ]
}
